[package]
name = "evaluator"
version = "1.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "evaluator"

[dependencies]
anyhow = "1.0.70"
slice-group-by = "0.3.0"
config = "0.13.3"
lazy_static = "1.4.0"
rayon = "1.7.0"
regex = "1.7.3"

[dev-dependencies]
pretty_assertions = "1.3.0"

[package.metadata]
cargo-test = ["--", "--test-threads=1", "--show-output"]
