is_prod: false
notifications:
  host: 'localhost'
  port: 9999
  channel: 'channel_1'
upstream:
  uri: "http://localhost:2121"
cache:
  host: 'localhost'
  port: 6379
  channel: 'channel_1'
rabbitmq:
  host: 'localhost'
  queue: 'submissions'
  consumer: 'consumer_2'
  port: 8778
postgres:
  host: '127.0.0.1'
  user: 'postgres'
  database: 'juezguapa'
  port: 8787
  password: 'postgres'
evaluator:
  playground: '/Users/yollotl/guapa/judge/juez_guapa/backend/evaluator/playground'
  resources: '/Users/yollotl/guapa/judge/juez_guapa/backend/testcaseFTP/resources'
  nsjail_config: '/Users/yollotl/guapa/judge/juez_guapa/backend/evaluator/resources/nsjail.cfg'
language:
  cpp17:
    path: '/opt/homebrew/bin/g++-14'
    args:  ['-std=c++1z', '$file', '-o', '$executable']
    eval_type: 'compiled'
    file_type: 'cpp'
  cpp11:
    path: '/opt/homebrew/bin/g++-14'
    args:  ['-std=c++11', '$file', '-o', '$executable']
    eval_type: 'compiled'
    file_type: 'cpp'
  python3:
    path: '/opt/homebrew/bin/python3'
    args:  ['$file']
    eval_type: 'interpreted'
    file_type: 'py'
  java:
    path: '/usr/bin/javac'
    args:  []
    eval_type: 'java'
    file_type: 'cpp'
  cmp:
    path: '/usr/bin/cmp'
    args:  []
    eval_type: 'interpreted'
    file_type: ''
postgres_queue:
  queue: 'submission_queue'
  notification_channel: 'submission_channel'
