is_prod: true
redis:
  host: 'host.docker.internal'
  port: 9999
  channel: 'channel_1'
rabbitmq:
  host: 'host.docker.internal'
  queue: 'submissions'
  consumer: 'consumer_1'
  port: 8778
postgres:
  host: 'host.docker.internal'
  user: 'postgres'
  password: 'password'
  database: 'juezguapa'
  port: 8787
